# Generated by Django 3.2.7 on 2021-10-22 20:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_message_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
